### ISSUE TITLE
Groundtruth poses of SubPipe

### ISSUE THREAD

**Issue by sit-mmc** [olayasturias/monocular_visual_slam_survey#3]
Hi, thanks for your work !

I wonder if you could release groundtruth poses of SubPipe or the code generating the poses (like in COLMAP format) as well.

Thank you.

**Comment by olayasturias** [comment]
Hello, thank you for your interest in this repo!
The relevant information about SubPipe can be found under [this link](https://github.com/remaro-network/SubPipe-dataset), including the paper and the download link for the dataset itself.  The pose ground truth is within the file EstimatedState.csv

Regarding the pose format, I have already replied to a similar question [for issue 2 in SubPipe's repo](https://github.com/remaro-network/SubPipe-dataset/issues/2). 

Let me know if that helped :)
